import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar';
import LeftSidebar from './components/leftSidebar';
import RightSidebar from './components/rightSidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col md:flex-row'>
        <div className='hidden md:block'>
          {/* LeftSidebar - will only be visible from medium (md) breakpoint and above */}
          <LeftSidebar />
        </div>
        <div className='w-full'>
          {/* Navbar - always visible, taking full width */}
          <Navbar />
          <main className=''>{children}</main>
        </div>
        <div className='hidden md:block'>
          {/* RightSidebar - will only be visible from medium (md) breakpoint and above */}
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
