import type { Metadata } from 'next';
import './globals.css';
import { Navbar } from '@/components';

export const metadata: Metadata = {
  title: 'IRD Foundation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='overflow-hidden relative md:ml-[165px] md:mr-[40px] '>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
